bemfa:
  enabled: False
  uid: aaabbbcccdddeeefffggg
  topic: mypc001
devices:
  name: µçÄÔ
  ip: 192.168.100.100
  wol:
    enabled: True
    mac: 00-11-22-33-44-55
    destination: broadcast_ip_global
    port: 9
    interface: default
  shutdown:
    enabled: True
    method: 
      netrpc: True
      udp: False
      shell: False
    account: youraccount
    password: yourpassword
    shell_script: yourscript
    time: 60
  ping:
    enabled: True
    time: 60
functions:
  log:
    enabled: True
    level: 2
    clear_log: 
      enabled: False
      keep_days: 7
  push_notifications:
    enabled: False
    bemfa_reconnect: True
    ServerChan_turbo:
      enabled: False
      SendKey: YOUR SENDKEY
      channel: 9
    ServerChan3:
      enabled: False
      SendKey: YOUR SENDKEY
    Qmsg:
      enabled: False
      key: YOUR KEY
      qq: 123456789
    WeChat_webhook:
      enabled: False
      url: Ê¾Àý https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=xxxx